### ISSUE TITLE
scaling broken on firefox based browsers on mac

### ISSUE THREAD

**Issue by RekuNote** [jaames/flipnote.js#30]
tested on m1 macbook air on latest sonoma with both latest firefox and waterfox, both natively and under rosetta
<img width="667" alt="Screenshot 2024-05-28 at 9 07 44 AM" src="https://github.com/jaames/flipnote.js/assets/170186554/0cfb17f8-c872-4ab1-9065-3ba5ba00e31f">
(screenshot from https://www.reximemo.net/)
<img width="758" alt="Screenshot 2024-05-28 at 9 08 19 AM" src="https://github.com/jaames/flipnote.js/assets/170186554/c20f908b-44c8-4528-bd9f-be2961a62bcd">
(screenshot from https://gallery.kaeru.world/)
<img width="574" alt="Screenshot 2024-05-28 at 9 08 51 AM" src="https://github.com/jaames/flipnote.js/assets/170186554/11583dc7-263a-4385-bb6b-d0adca0427a1">
(screenshot from https://flipnote.js.org/)

**Comment by RekuNote** [comment]
it seems to be showing the flipnote at 256x192?

**Comment by jaames** [comment]
Seems like a bug / regression in Firefox itself, not sure where exactly it's coming from (don't have the time to debug super in depth right now) but I just pushed a quick workaround. It's probably some kind of internal WebGL texture sizing or viewport issue.

Have you tested in Firefox on any other systems? I'm on an Apple Silicon Macbook too, but wanna check if it's specific to Apple Silicon or if it affects Firefox more generally.

**Comment by RekuNote** [comment]
I've tested this with FireFox on Manjaro Linux, no issue

**Comment by jaames** [comment]
Finally solved this in a way that should be consistent for all sizes / dpi combinations. It seems that Firefox has some kind of bug in how it handles DPI scaling in respect to the gl.viewport coordinates maybeee?
